
DELETE  http://localhost:3001/api/persons/2
###
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name": "aeyytHJffh3345345ghjrtgyh45K345",
    "number": "1456456"
}
###
GET http://localhost:3001/api/persons